### ISSUE TITLE
Can Gannet process GE DICOM (.dcm)？

### ISSUE THREAD

**Issue by houcy123** [markmikkelsen/Gannet#12]
Can Gannet process GE DICOM (.dcm)？

![MRS](https://user-images.githubusercontent.com/126129732/220808607-b7fc73ed-c324-448a-ab5d-d52fb7275ac6.png)

**Comment by markmikkelsen** [comment]
GE MRS files are exported as P-files. They are (normally) saved on the console in `/usr/g/mrraw`

**Comment by houcy123** [comment]
We have lost the p-files and only have DICOM. Can Gannet process DICOM?

**Comment by markmikkelsen** [comment]
Yes, please refer to the [documentation website](https://markmikkelsen.github.io/Gannet-docs/getting-started.html#dicom-data-.dcm-files) for details. However, I believe GE only saves a single DICOM file with a single summed spectrum, which will make the preprocessing difficult as Gannet expects the averages to be stored separately.

**Comment by houcy123** [comment]
Thank you very much. I have another question. Does GENNET3.3.0 have a user interface? I don't know how to call it.

**Comment by markmikkelsen** [comment]
We are currently working on a GUI, but it is not available yet. It should be in the next stable release.
