### ISSUE TITLE
Error on frqbounds on SIEMENS and Philips

### ISSUE THREAD

**Issue by chavilaffitte** [markmikkelsen/Gannet#13]
Having issues with HERMES Philips data in both raw and sdat/spar formats. Additionally, the same things happen when trying to process MEGAPRESS data from SIEMENS in .dat format. 

![Screenshot 2023-02-24 at 11 35 24 AM](https://user-images.githubusercontent.com/69527787/221234821-629f4c64-5e7a-4bae-bb1c-3c07c3a71bcb.png)

**Comment by markmikkelsen** [comment]
Could you please provide screenshots of the GannetLoad output?

**Comment by chavilaffitte** [comment]
[data.zip](https://github.com/markmikkelsen/Gannet/files/10832102/data.zip)

**Comment by markmikkelsen** [comment]
Your data are corrupted. I suspect what happened is that "Apply Spectral correction" in the _Postproc_ tab in the Philips scanner GUI was set to `yes`. See below.

Please check your exam card parameters and/or reach out to the Johns Hopkins team for support with their patch.

![6_Postproc](https://user-images.githubusercontent.com/6051303/221376621-f6d9d7ff-ceda-46f5-ac62-42369f766f93.jpg)

**Comment by chavilaffitte** [comment]
Thanks so much. For the future, how can I tell? Given the data has already been acquired.
Also, GANNET works with some of the raw(.data/.list) (see the exact same subject below); but not others even when it is the same sequence/patch/scanner and sometimes even the same subject on the same day.  


![Screenshot 2023-02-25 at 3 07 32 PM](https://user-images.githubusercontent.com/69527787/221377484-6c25d7fb-f415-45a9-882c-34889b3abbe6.png)

**Comment by markmikkelsen** [comment]
If you look at the data inside the output structure, specifically `MRS_struct.fids.data`, you will see most of the data is zero or near zero. However, it is best practice to double-check that your scan parameters have not changed each time you scan (this happens more often than one might think).

If you have the .data/.list files for the same scans for which you have .sdat/.spar files, then there is a possibility the data were exported correctly in the raw files (but please contact the Hopkins team to confirm). However, I don't believe we have updated the data loading for such data for HERMES acquisitions. I would need to have some example data to check the code.

**Comment by chavilaffitte** [comment]
I realized that I can correctly load and fit the raw data as long as I have the act.SPAR file in the same folder or in path. Does that make sense? File size in raw is too big. I can send to you some other way

**Comment by markmikkelsen** [comment]
Yes, you need the .SPAR file, as the raw files do not contain any information about the scan parameters (which Gannet needs). My email is mam4041@med.cornell.edu if you want to send the data through a file share service.
