### ISSUE TITLE
Missing dicom header parameter with version 3.3.0

### ISSUE THREAD

**Issue by julfou81** [markmikkelsen/Gannet#14]
Hi,
Thank you for providing and maintaining such a useful tool!

We recently came across the following issue:
GannetLoad was complaining about a missing parameter in the DICOM header: `DicomHeader.editRF.centerFreq`

We did not get this error with Gannet version 3.1.5.

This is due to this change in 'SiemensDICOMHeader.m' .

In version 3.1.5:
```
if isfield(MRS_struct.p, 'Siemens')
    MRS_struct.p.Siemens.deltaFreq = DicomHeader.deltaFreq;
    MRS_struct.p.Siemens.editRF.freq = DicomHeader.editRF.freq;
    MRS_struct.p.Siemens.editRF.bw = DicomHeader.editRF.bw;
    MRS_struct.p.Siemens.editRF.centerFreq = DicomHeader.editRF.centerFreq;
end
```

In version 3.3.0:
```
if isfield(DicomHeader, 'editRF')
    MRS_struct.p.deltaFreq         = DicomHeader.deltaFreq;
    MRS_struct.p.editRF.freq       = DicomHeader.editRF.freq;
    MRS_struct.p.editRF.bw         = DicomHeader.editRF.bw;
    MRS_struct.p.editRF.centerFreq = DicomHeader.editRF.centerFreq;
end
```

Our Siemens dicom (coming from a 3T Prisma with Syngo VE11C) headers have indeed a field `editRF` with fields `freq` and `bw` but not `centerFreq`. In version 3.1.5, since the Field `Siemens` was not present, this loop was not used.

The workaround I did for now is to comment the line:
```
%MRS_struct.p.editRF.centerFreq = DicomHeader.editRF.centerFreq;
```

**Comment by markmikkelsen** [comment]
Thanks for bringing this up. This bug has already been identified and fixed in the [development version](https://github.com/markmikkelsen/Gannet/tree/dev), specifically commit d321e3a31ee27d72a74a456ca02bde55f45d535f. This fix will be added to the next stable release.
