### ISSUE TITLE
[BUG] Issue with sprintf in Windows-Matlab

### ISSUE THREAD

**Issue by franciscofritz** [markmikkelsen/Gannet#23]
### Contact details

f.lagosfritz@uke.de

### Describe bug

Hi,
I am running Ganner to analyse .dat Siemens MRS data file using Matlab R2019b in Windows 10.  I load the data located in the following path: F:\Leipzig_20181101\mrs_raw\28998.75_181101_112048\(.,..) but the program complains about the sprintf function. Even though this seems to be predominantly a Matlab problem, I have never had an issue with sprintf for any of my folders's name. Actually, I have changed the name of the main folder several times, but it always complains about this "escaped character". 

I want to know if it is a Windows problem, Matlab problem or somehow the "path" I add into the GannetLoad should be a string instead of a char array (and maybe that complains about the folder's name).

### Screenshots

Warning: ********** An error occured while loading dataset:
'F:\Leipzig_20181101\mrs_raw\28998.75_181101_112048\meas_MID131_svs_st_FID40704.dat'. Check data.
Skipping to next dataset in batch ********** 
> In GannetLoad (line 723) 
Warning: Escaped character '\L' is not valid. See 'doc sprintf' for supported special characters. 
> In GannetLoad (line 724) 

### Version

3.3.1

### Operating system

Windows

### MATLAB version

R2019b

**Comment by franciscofritz** [comment]
Ok, I have tried with smaller paths and the problem is the same. Is it the problem with F:\ or the "\" on Windows?

**Comment by markmikkelsen** [comment]
Hi @franciscofritz,

I've added a bug fix for backslashes in filenames (5b91ba2e643a565e914324f8e911e2dc7b54b049). Please update and try again to see if the bug persists.

**Comment by markmikkelsen** [comment]
@franciscofritz, has the fixed resolved the bug?

**Comment by franciscofritz** [comment]
Hi. Actually not yet. Now it does not report the warning, however it still appears this pop-up window that says: 
![grafik](https://user-images.githubusercontent.com/23002422/227941242-50bfb71b-cd20-4425-88c2-fa64866cd885.png)

**Comment by markmikkelsen** [comment]
Are you able to share your data? My email is mam4041@med.cornell.edu. There's an error occurring that I cannot determine from that error message alone.

**Comment by markmikkelsen** [comment]
Also, which version of Windows are you using?

**Comment by markmikkelsen** [comment]
I've added another change to the code that I hope will resolve the issue. Please update and rerun your data.

**Comment by franciscofritz** [comment]
Hi! 

OK, sadly I can't share the data because is not "mine" (or acquired by me). But going through the debugging, the problem arises in mapVBVD_Gannet. And I think why this could be. The data I am using was acquired using Siemens VE11C version (I think, unless it is already VAX). I had also the mapVBVD function and I had to modify it time ago to reconstruct data acquired with VE version. 
I will update once again but if the error comes from the map VBVD then it is not too much to do. I am using Windows 10 and Matlab R2019b.

Thanks.

**Comment by markmikkelsen** [comment]
Thanks for the update. If you are able to provide what modifications you made to mapVBVD for version VE, that would be very helpful for Gannet.

Please let me know if the updated version has at least resolved the error dialog issue.

**Comment by franciscofritz** [comment]
Ok, let me work on it. I cannot promise to deliver results today or tomorrow, but for sure Monday if it is ok for you.

:) - and I will let you know if with the correction the code can go through.

**Comment by franciscofritz** [comment]
Ok, found the error error (at the end it was not in the mapVBVD, sorry for the misunderstanding). In SiemeneTWIXRead.m, line 316, 

TwixHeader.seqorig = TwixHeader.sequenceString;
 error(['Unknown sequence: ' TwixHeader.seqorig '. Please contact the Gannet team for support.'])

The sequence used is 
K>> TwixHeader.sequenceString

ans =

    'svs_st'

(or STEAM-based spectroscopy). Since it is not part of the "list" of sequence's name, then it goes to error.

**Comment by franciscofritz** [comment]
Oh... I see. Ok, let me see if I can check out with another dataset (or edited data). I will keep you posted (probably I will update this comment).
