### ISSUE TITLE
[BUG] co-registration doesn't work properly in newer versions

### ISSUE THREAD

**Issue by peter-mri** [markmikkelsen/Gannet#24]
### Contact details

peter.seres@ualberta.ca

### Describe the bug

We have used Gannet 3.0 to co-register .rda spectra (PRESS in muscle, not MEGA-PRESS) on anatomical images and it works fine. However it doesn't work properly in 3.3.x. Not sure f relevant, but noticed that newer version reports voxel dimensions flipped compared to old version.

### Steps to reproduce the bug

disp('Loading spectra');
MRS_Struct=GannetLoad({rda_file});
MRS_Struct.ii=1; % trick Gannet to use any spectra, not just MEGAPRESS
MRS_Struct.p.numScans=1; % trick Gannet 3.3 to use any spectra
disp('Co-registering');
MRS_Struct=GannetCoRegister(MRS_Struct,{anat_file});

### Screenshots

![3p0](https://user-images.githubusercontent.com/63120314/227650819-517908f3-42ff-4355-bee6-583daaaae151.jpg)
![3p3p1](https://user-images.githubusercontent.com/63120314/227651169-323ce38f-c769-4fb9-b817-614e1dc497a9.jpg)

### Version

33.1

### Operating system

Windows

### MATLAB version

R2022b

**Comment by markmikkelsen** [comment]
Hi @peter-mri,

Firstly, .rda is not recommended. It's much better to export your data in TWIX (.dat) format.

Secondly, if you are co-registering MRS voxels that are not from edited acquisitions, you should use `CoRegStandAlone.m`. See these [instructions](https://markmikkelsen.github.io/Gannet-docs/additional-tools.html#coregstandalone) for details.

Note that for muscle data, the segmentation will not be appropriate as the SPM template is for the adult brain. Happy to help you adjust this if you want to segment your images/MRS voxels for muscle (if there's an appropriate template available).

**Comment by markmikkelsen** [comment]
Are you able to share your data so I can explore the problem in the newer version? My email is mam4041@med.cornell.edu
