### ISSUE TITLE
Explanation for discrepancy in output between versions?

### ISSUE THREAD

**Issue by peter-mri** [markmikkelsen/Gannet#25]
I totally understand that for every study, single version of a particular software should be used for analysis. We have used (and published) analysis using Gannet 3.0. I like some of the improvements in peak alignment in newer version(s), but I find the reported difference in values of GABA/Cr somewhat shocking. Was there a change in fitting procedure as well? 

[MEGAPRESS_GABA_MPFC_noMM_GABAGlx_fit.pdf](https://github.com/markmikkelsen/Gannet/files/11067084/MEGAPRESS_GABA_MPFC_noMM_GABAGlx_fit.pdf)
[MEGAPRESS_GABA_MPFC_noMM_vox1_fit.pdf](https://github.com/markmikkelsen/Gannet/files/11067059/MEGAPRESS_GABA_MPFC_noMM_vox1_fit.pdf)

**Comment by markmikkelsen** [comment]
The 171013 fit version shows poorer data quality compared to the 230317 fit version, showing improvements in the software. Changes in results from software updates are expected.
