### ISSUE TITLE
update GERead.m to include rdbm_rev_num 30.x

### ISSUE THREAD

**Issue by hfxcarl** [markmikkelsen/Gannet#28]
Hi, I've just collected a GE Pfile.7 with PRESS Seq with TE=30 following the console update to rdbm_rev_num=30.("SoftwareVersions": "30_LX_SIGNA_LX1.MR30.0_R01_2242.a").Gannet-3.3.1 throws an error that "GERead.m is not fully functional with header revision number 30." How can I help get Gannet updated to read the new format?
Cheers,
Carl
![Screenshot 2023-07-28 at 16 47 13](https://github.com/markmikkelsen/Gannet/assets/18428794/a3e252e7-d9a9-4b8a-80d7-43d399c0665c)

**Comment by markmikkelsen** [comment]
Hi @hfxcarl,

I've added support for rdbm_rev_num 30. However, please note that Gannet does not support non-edited PRESS data. Only edited data (e.g., MEGA-PRESS).

Mark

**Comment by hfxcarl** [comment]
Thanks @markmikkelsen! I've just tested this and Gannet-v3.3.2 now reads GE rev.30 Pfiles. I'm only using Gannet to plot the VOI on T1w and run a quick tissue segmentation with SPM12. Cheers
