### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by michaelf500** [markmikkelsen/Gannet#30]
Hello

In the documentation 
https://markmikkelsen.github.io/Gannet-docs/getting-started.html

Under the description of how to load dicom files, the example code is:

`MRS_struct = GannetLoad(metab({'metab/file1.ima'}, {'water/file1.ima'});
`

the `metab(`
bit is not needed (and doesn't work). Instead, I think it should be 

`MRS_struct = GannetLoad({'metab/file1.ima'}, {'water/file1.ima'});
`

Thanks

Michael

**Comment by markmikkelsen** [comment]
Thanks for catching this! I've corrected it on the website.

Mark
