### ISSUE TITLE
[BUG] PaperPlot error when trying to plot spectrum and fit

### ISSUE THREAD

**Issue by tkhauser** [markmikkelsen/Gannet#35]
### Contact details

tkhauser@onlinehomenet.de

### Describe the bug

I am working with a GABA edited MEGA-PRESS sequence on a Siemens machine (3T Vida Fit, XA50)
Evaluation is done on a Mac in MATLAB2024A, v3.4.0-dev (also tried Gannet v3.3.2)
Loading, fitting, coregistration, segmentation and Quantification work perfectly, no errors.
Also "PaperPlot(MRS)" runs fine but when I try to do something like 
PaperPlot(MRS, 'plotModel', true);
I get the following error 

Unrecognized field name "GABAGlx".
Error in PaperPlot (line 258)
                    resid = (real(MRS_struct.spec.(vox{ii}).(target{jj}).(diff)(specNum(kk),residInd)) - (model(MRS_struct.out.(vox{ii}).(target{jj}).ModelParam(specNum(kk),:),modelFreq) ./ scaleFactor(kk))) - baseMeanResid(kk,:); 

### Steps to reproduce the bug

metab = {'meas_MID00440_FID22059_svs_edit_30isoGABA.dat'};
water = {'meas_MID00446_FID22065_svs_se_noWS.dat'};
anat  = {'t1_12001.nii'};
MRS = GannetLoad(metab, water);
MRS = GannetFit(MRS);
MRS = GannetCoRegister(MRS,anat);
MRS = GannetSegment(MRS);
MRS = GannetQuantify(MRS);
PaperPlot(MRS, 'plotModel', true);

### Screenshots

![Bildschirmfoto 2024-09-25 um 10 25 10](https://github.com/user-attachments/assets/d4fe9b6c-de22-43ca-84a1-29c1f06b0fee)

### Gannet version

Gannet v3.4.0-dev and  Gannet v3.3.2

### MATLAB version

R2024A

### Operating system

macOS Sequoia15

**Comment by markmikkelsen** [comment]
Hi @tkhauser,

Thanks for catching this bug. I've corrected it on the [dev](https://github.com/markmikkelsen/Gannet/tree/dev) branch (e75a7fd).

Mark
